import NavBar from "@/components/NavBar";
import CategoryBar from "@/components/CategoryBar";
import { M_PLUS_Rounded_1c } from "next/font/google";
import "./globals.css";

const m_plus_rounded = M_PLUS_Rounded_1c({ subsets: ["latin"], weight: ['100', '300', '400', '500'] });

export const metadata = {
  title: "Jeansin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={m_plus_rounded.className}>
        <NavBar/>
        <CategoryBar/>
        {children}
      </body>
    </html>
  );
}
